### PR TITLE
serversoftware not cilentversion

### PR DESCRIPTION
**Pull request by pooooooon**

### CODE REVIEW

**Review by ItzLightyHD — CHANGES_REQUESTED** [review]
Can you update it to show the the strings from the PocketMine class file?

**Comment by Quaterizer** [comment]
Please Update

**Comment by ItzLightyHD** [comment]
> 
> 
> Please Update

Don't worry, we're doing the job :)

**Review by ItzLightyHD — COMMENTED** [review]
Wait, why did you remove things from the decodePayload() function?

**Comment by pooooooon** [comment]
the decodePayload() on startgamepacket it not be use and startgamepacket is server send only

**Pull request closed without merging**
